### ISSUE TITLE
Perhaps a better way to solve the issue of third-party custom weapon plugins.

### ISSUE THREAD

**Issue by GrangKing** [hollacs/Gun-Tracer-AMXX#1]
The parameter entity in OnFireBuckshots and OnFireBullet3 should be able to be replaced by pevAttacker, which may not cause server crashes due to third-party weapon plugins. Sorry, my English is not good.

**Comment by hollacs** [comment]
yes, I've noted this too, I'll fix this when I have time.

**Comment by GrangKing** [comment]
😃Okay. I will close this issue.
